### ISSUE TITLE
Is it possible to hook up rq-dashboard to arq?

### ISSUE THREAD

**Issue by dazza-codes** [samuelcolvin/arq#219]
rq and arq noobie... apologies in advance if this is covered already elsewhere, pointers appreciated.

Thanks for arq, seems like a good idea.  In some respects, it would be great if rq and arq shared a common programming API, with the exception of the asyncio coroutine patterns.  In various respects, arq is not following the same API as rq, aside from the asyncio coroutine patterns; e.g. the enqueue function signature is different and the job status details are different.  It seems like arq does not use a 'default' queue by default.

It seems like rq-dashboard is not hooked up, an arq worker does not show up as registered in rq-dashboard.  Is it possible to use rq-dashboard with arq?  Is this documented?  Does this have anything to do with inconsistency in the programming APIs?

I was able to get some arq code working after a few debug-RTFM cycles to adapt some rq code to arq.  It was a bit tricky, but it works with docker-compose, e.g.

```yaml
# This is inspired by https://github.com/jaredvasquez/rq-docker

version: '3.7'
services:
  rq-server:
    image: redis:alpine
    ports:
      - 6379:6379

  rq-dashboard:
    image: test-arq
    depends_on:
      - "rq-server"
    command: rq-dashboard -H rq-server
    ports:
      - 9181:9181

  arq-worker:
    image: test-arq
    depends_on:
      - "rq-server"
    command: arq test_arq.WorkerSettings
    environment:
      - REDIS_DSN=redis://rq-server:6379
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}
```

However, the rq-dashboard is useless with arq, or have I missed something?  The worker setup is like

```python
# test_arq.py
# imports snipped out

def get_redis_settings() -> RedisSettings:
    redis_dsn = os.getenv("REDIS_DSN")
    LOGGER.info("redis_dsn: %s", redis_dsn)
    if redis_dsn:
        return RedisSettings.from_dsn(redis_dsn)
    else:
        return RedisSettings()

# etc etc etc
# assume that `async_test_arq` func is defined and working as expected
# and that it can successfully enqueue jobs to the "test" queue

# WorkerSettings defines the settings to use when creating the work,
# it's used by the arq cli, see options in docs at
# https://arq-docs.helpmanual.io/#arq.worker.Worker
class WorkerSettings:
    functions = [async_test_arq]
    on_startup = startup
    on_shutdown = shutdown
    redis_settings = get_redis_settings()
    queue_name = "test"
```
